### ISSUE TITLE
outline color

### ISSUE THREAD

**Issue by cheh** [CherryFramework/cherry-framework#112]
Maybe set more lightest color

https://github.com/CherryFramework/cherry-framework/blob/prerelease/modules/cherry-interface-builder/inc/assets/cherry-interface-builder.scss#L81

![113fd48aeef74603a11a867ba42a150c](https://cloud.githubusercontent.com/assets/2461627/19524379/2f0bdea6-9626-11e6-8ac7-d8957bb93489.png)

**Comment by MaksimTS** [comment]
I think, border color of text area section would be great.

**Comment by MakhonkoDenis** [comment]
Done. Change outline color.
