### ISSUE TITLE
Ошибка при поиске продуктов

### ISSUE THREAD

**Issue by leshamakar** [CherryFramework/cherry-framework#129]
Ошибка при поиске продуктов http://prntscr.com/d8gjlr 
Установлен Чери серч
Поиск при помщи Вукомерсовского поиска

**Comment by shinTM** [comment]
Смотрите плиз, куда пишете ишусы. "Установлен Чери серч", "Поиск при помщи Вукомерсовского поиска" ишус во фреймворке

**Comment by cheh** [comment]
And the issue goes to ... https://github.com/CherryFramework/cherry-search/issues/3

**Comment by MakhonkoDenis** [comment]
https://github.com/CherryFramework/cherry-search/issues/3
