### ISSUE TITLE
Changing project archive name/location

### ISSUE THREAD

**Issue by parappara** [CherryFramework/cherry-framework#133]
Hello,

How do I change the location of the projects from /projects-archive/projectname to something else? The option doesn't exist in Settings.

**Comment by shinTM** [comment]
It's not a framework ussue, if i'm not mistaken. Hovewer, you can change slug using this filter https://github.com/CherryFramework/cherry-projects/blob/master/public/includes/class-projects-registration.php#L97
Write here, if something goes wrong

**Comment by parappara** [comment]
You're right. It's not an issue at all. I just didn't know where to ask support questions. Thanks for the help though:+1:
