### ISSUE TITLE
FontAwesome icon-pack hard coded inside the module

### ISSUE THREAD

**Issue by ghost** [CherryFramework/cherry-framework#16]
Methods on **line [80](https://github.com/CherryFramework/cherry-framework/blob/master/modules/cherry-post-types/inc/cherry-post-type.php#L80)** and on **line [97](https://github.com/CherryFramework/cherry-framework/blob/master/modules/cherry-post-types/inc/cherry-post-type.php#L97)** must be refactored because of icons should not be hard coded inside a module. There should be **an option** to use an icon-pack.

Changes in the file are present since this [commit](https://github.com/CherryFramework/cherry-framework/commit/042e6caae6ffdf359ce8953374a0699de1c44a8a).

Mentions: @gcofficial

**Comment by theguriev** [comment]
Nem értek egyet ezzel a

**Comment by shinTM** [comment]
"Я с этим не согласен" а если в проекте юзают материальные иконки и я хочу юзать модуль этот, мне подключать еще один ассет?  на данный момент там подключена версия 4,5,0 а сейчас актуальна 4,6,1 нет возможности юзать иконки, добавленные в этом промежутке версий

**Comment by theguriev** [comment]
А Вы разобрались с сутью? Это просто хелпер для девелопера котороый прикрепляет иконку к кастумному пост тайпу. Не более. 

Кому нужны другие иконки пусть расширяют класс, добавляют методы и т.д. Кто же мешает? Другие icon pack'и будут добавляться в css по другому. Мне для всех предусматривать? По этому и метод собственно назван font_awesome_icon. 

Пример использования:
`$this->core->modules['cherry-post-types']->create(
            'property',
            'Properties',
            'Property',
            array(
                'supports' => array(
                    'title',
                    'editor',
                    'author',
                    'thumbnail',
                    'excerpt',
                    'comments',
                ),
            )
        )->font_awesome_icon( 'f1ad' );`

**Comment by ghost** [comment]
@gcofficial 

То-есть чтобы юзать твой модуль надо писать ещё один модуль, который будет наследовать твой? Почему нельзя сделать это опцией? Что будет если мне нужно 10 паков иконок сразу? 10 модулей делать?

В итоге будет +100500 методов для каждого пака иконок?

``` php
$this->core->modules['cherry-post-types']->create( 'property', 'Properties', 'Property', array( 'supports' => array( 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'comments', ), ) )->mega_icon( 'f1ad' );

$this->core->modules['cherry-post-types']->create( 'property', 'Properties', 'Property', array( 'supports' => array( 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'comments', ), ) )->avadakedabra_icon( 'f1ad' );
```

**Comment by theguriev** [comment]
Да! Потому что вывод этих иконок разный:
FontAwesome =`<i class="fa fa-gitlab"></i>`
Material = `<i class="material-icons">find_replace</i>`
Custom = `<img src="my-custom.png">`
Custom2 = `<i class="super-icon"></i>`

Если есть другой вариант, предлагай. Тебе же никто не мешает. Так ведь?

**Comment by ghost** [comment]
@gcofficial 

Проще добавить новый фильтр чем создавать новый модуль только ради нового вывода.

Есть функция [apply_filters](https://developer.wordpress.org/reference/functions/apply_filters/) и тогда отдельный метод не требуется.

[В эту функцию](https://github.com/CherryFramework/cherry-framework/blob/master/modules/cherry-post-types/cherry-post-types.php#L90) передавать иконку через аргумент `$args` (The custom post type arguments).

**Comment by theguriev** [comment]
Кто-то говорил о новом модуле? Речь идет о методе. 

передавать иконку через аргумент $args --- а если это картинка, текст, класс или svg? Ты хочешь чтобы я все варианты продумал для всех возможных выводов иконки для пост - тайпа? 
Да и... Ещё раз... Тебе кто-то мешает это сделать?

**Comment by shinTM** [comment]
FontAwesome =<i class="fa fa-gitlab"></i>
Material = <i class="material-icons">find_replace</i>
Custom = <img src="my-custom.png">
Custom2 = <i class="super-icon"></i>

все верно это ты перечислил 4 возможных варианта опции иконки

**Comment by shinTM** [comment]
это ревью а не указания как делать, будет так как реализовал автор.
