### ISSUE TITLE
radio field on ui-repeater

### ISSUE THREAD

**Issue by danryl12344** [CherryFramework/cherry-framework#176]
It seems there is an issue regarding with the radio field on ui-repeater. When I dragged/re-order the ui-repeater items, checked radio item will be unchecked. 

Please check the screenshot

Before re-ordering ui-repeater item
https://www.screencast.com/t/93sFzFeF

After re-ordering ui-repeater item
https://www.screencast.com/t/1N8VTIVf

**Comment by MjHead** [comment]
Hi @danryl12344 
Thanks for report. We'll try fix this ASAP

**Comment by danryl12344** [comment]
Thanks for your help.

**Comment by danryl12344** [comment]
@MjHead any update for this issue ?

**Comment by MjHead** [comment]
A lot of work... will be done in a few days.

03 авг. 2017 г. 5:02 пользователь "danryl12344" <notifications@github.com>
написал:

**Comment by MjHead** [comment]
https://github.com/CherryFramework/cherry-framework/commit/00ea2232e768801deaf8263da37795658e737391

**Comment by danryl12344** [comment]
@MjHead it is now working :) thanks for this awesome framework.
