### ISSUE TITLE
Cherry UI Controls broken

### ISSUE THREAD

**Issue by ghost** [CherryFramework/cherry-framework#20]
On line [164](https://github.com/CherryFramework/cherry-framework/blob/master/modules/cherry-ui-elements/cherry-ui-elements.php#L164) there is a special check for if the control class implements the `I_UI` interface.

On some environments and in case of any errors occurred, while running the [`class_implements`](http://php.net/manual/en/function.class-implements.php) function,
it will return an empty array or `false` and the code inside the `if` statement will be omitted. This behavior will lead to UI controls assets not being loaded.

Refactoring of the code required.

CC: @CherryFramework/developers

**Comment by MakhonkoDenis** [comment]
Done
