### ISSUE TITLE
Delete ui-elements

### ISSUE THREAD

**Issue by MakhonkoDenis** [CherryFramework/cherry-framework#58]
Need delete next ui elements:
- [ui-chooseicons](https://github.com/CherryFramework/cherry-framework/tree/develop/modules/cherry-ui-elements/inc/ui-elements/ui-chooseicons)
- [ui-collection](https://github.com/CherryFramework/cherry-framework/tree/develop/modules/cherry-ui-elements/inc/ui-elements/ui-collection)
- [ui-number](https://github.com/CherryFramework/cherry-framework/tree/develop/modules/cherry-ui-elements/inc/ui-elements/ui-number)

**Comment by shinTM** [comment]
dene https://github.com/CherryFramework/cherry-framework/pull/59
