### ISSUE TITLE
UI Media upload button visible for users without upload_files capability

### ISSUE THREAD

**Issue by ghost** [CherryFramework/cherry-framework#81]
UI Media upload button visible for users without `upload_files` capability.
If user has no `upload_files` capability, the button shouldn't be rendered.

References:
- [Roles_and_Capabilities#upload_files](https://codex.wordpress.org/Roles_and_Capabilities#upload_files)
- [current_user_can()](https://developer.wordpress.org/reference/functions/current_user_can/)

**Comment by MakhonkoDenis** [comment]
Done
