### ISSUE TITLE
HTML tags in post title

### ISSUE THREAD

**Issue by cheh** [CherryFramework/cherry-framework#93]
The post title need renders the words with html tags like `em`, `strong`.
E.g. in `Twenty Sixteen` theme:

![screenshot_2](https://cloud.githubusercontent.com/assets/2461627/18125269/345fa1a4-6f7e-11e6-9ac6-0ae95c3394dc.png)

https://github.com/CherryFramework/cherry-framework/blob/master/modules/cherry-utility/inc/cherry-attributes-utilit.php#L55

**Comment by shinTM** [comment]
https://github.com/CherryFramework/cherry-framework/commit/8d248ce08690da9ac71ca46e9bd9375b90e9467d
