### ISSUE TITLE
Argument 'class' for UI elements not working

### ISSUE THREAD

**Issue by MjHead** [CherryFramework/cherry-framework#95]
https://github.com/CherryFramework/cherry-framework/blob/develop/modules/cherry-ui-elements/inc/ui-elements/ui-media/ui-media.php#L38, 
https://github.com/CherryFramework/cherry-framework/blob/develop/modules/cherry-ui-elements/inc/ui-elements/ui-media/ui-media.php#L63-L65

**Comment by MakhonkoDenis** [comment]
Done
